
[cluster]
    domain = "10"
    id = "24001"

[apollo]
    app_id = "apigateway"
    cluster = "default"
    namespaces = ["config.yaml","global.properties"]
    meta_addr = "http://10.155.20.189:8180"
    cache_dir = "."
    